name: Deploy Docker a Elastic Beanstalk

on:
  push:
    branches: [ "main" ]

# Permisos necesarios para subir paquetes a GitHub Container Registry
permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Bajar el código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configurar Java 25
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Compilar
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Login en GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Calcular nombre de imagen en minúsculas (Requisito de Docker)
      - name: Lowercase Image Name
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      # 6. Construir y Subir Imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}

      # 7. Generar archivo docker-compose.yml
      # Este es el estándar moderno para Amazon Linux 2023.
      # Mapea el puerto 80 (Internet) al 8080 (Tu Spring Boot)
      - name: Generate docker-compose.yml
        run: |
          echo "services:
            app:
              image: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
              ports:
                - '80:8080'
              restart: always" > docker-compose.yml

      # 8. Desplegar en AWS Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          region: us-east-1
          application_name: BancoAPI      # Tu nombre de App
          environment_name: BancoAPI-env  # Tu nombre de Entorno
          version_label: "banco-v-${{ github.run_number }}"
          deployment_package: docker-compose.yml